language: generic
sudo: required

services:
  - docker #automatically retrieves a copy of docker to use

before_install:
  - docker build -t lorenzofasano96/docker-react -f Dockerfile.dev . # how to copy and reuse the id of the build? create tag

script:
  - docker run -e CI=true lorenzofasano96/docker-react npm run test -- --coverage # assumes this is either working or not

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-100885563533"
  bucket_path: "docker-react"
  on:
    branch: master # deploy only when changes appen on master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
