version: "3"

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #this means do not map a folder to node module inside container
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #placeholder to avoid overriding
      - .:/app
    command: ["npm", "run", "test"]
